### ISSUE TITLE
Message Cell Overlap with each other

### ISSUE THREAD

**Issue by zwang** [badoo/Chatto#119]
@diegosanchezr 

In the message view, when I click a message bubble which  presents another view controller in landscape mode by calling `vc.presentViewController(landscapeVC, animated: false, completion: {})`. However, when I exit the landscape view (also scroll to the bottom since it was original at the bottom), some of the messages overlapping with other messages. It seems to me the messages at bottom are move above to overlap with others. I am going to have a minimum re-producible demo soon. But before that, I am wondering if you have a quick tip about what might cause the issue. And where I can take a look at. It is related to the recent changes in this commit (https://github.com/zwang/Chatto/commit/e9b20e01de2f36eeaa4323f3fc8d0799db4de98d). 

Thanks

**Comment by diegosanchezr** [comment]
I'd blame the change in `collectionViewContentSize`, that change was made to avoid hitting an assert later on in `layoutAttributesForItemAtIndexPath` that we were seeing (iOS 8 only). Looking forward to that demo project so we can get the right fix.

**Comment by zwang** [comment]
Hi @diegosanchezr

Thanks for the tips. I was trying to re-produce the issue in ChattoApp, I could re-produce the exact bubble message overlapping issue, probably because it only happens on my custom bubble messages. However, there is another issue which is the reason why I need to scroll down to the bottom if it was at the bottom before. I have put some demo code here in ChattoApp: https://github.com/zwang/Chatto/commit/ff49a1001043d04ca1a9d67656bfa7069e331053. You can see it by click one of text messages to go to landscape demo view and then go back to the chat view. You will see the scrolling position is not maintained. I have put a workaround in “DemoChatViewController” line 51-70, you can uncomment the code to see the workaround. It is not an ideal solution IMHO. 

Thanks again for your help. I am going to continue look into my issue to see if I can find anything wrong and update this ticket. Cheers!

**Comment by diegosanchezr** [comment]
Too bad we can't reproduce the overlapping. Does it go away by reverting the changes in `collectionViewContentSize`?. Hopefully it's not Chatto's bug...

I've investigated a little bit the issue with the scroll position. I've seen that the chat controller get's rotated a few times when your landscape view controller is presented, which is not a very nice thing of UIKit... We currently handle "regular" rotation inside `viewWillTransitionToSize` (for your case `willTransitionToTraitCollection` is being called instead) but we're being rotated later on again without further notifications.

I got a PoC that actually fixes the issue:

```swift
public override func invalidateLayoutWithContext(context: UICollectionViewLayoutInvalidationContext) {
    guard let layoutModel = self.layoutModel, delegate = self.delegate else {
        super.invalidateLayoutWithContext(context)
        return
    }
    let oldContentSize = layoutModel.contentSize
    self.layoutModel = delegate.chatCollectionViewLayoutModel()
    self.layoutNeedsUpdate = false
    let contentSizeDiff = self.layoutModel.contentSize.height - oldContentSize.height
    context.contentOffsetAdjustment = CGPoint(x: 0, y: contentSizeDiff)
    super.invalidateLayoutWithContext(context)
}
```

Things missing there:
1. Custom UICollectionViewLayoutInvalidationContext: so that's only triggered for bounds change
2. Implement the logic in `viewWillTransitionToSize` regarding `scrollToBottom` and `scrollToPreservePosition` insted of the naive contentSize diff.
3. Make sure the contentOffsetAdjustment doesn't make the final offset go beyond the insets (in the current code, if offset "is at the top" and contentSize shrinks due to rotation then the content would move upwards?)
4. Check if this plays well allong with `adjustCollectionViewInsets` on rotation...

Then maybe `viewWillTransitionToSize` can be deleted... although the good thing of having this logic in the view controller is that custom layouts don't need to care about that...

All that said, this bug is very low priority for us (kind of edge case, and we don't suffer from it :p) and I'm afraid this change may break things, so I'm not sure if I'll pursue it further for now. Feel free to give it a try, although if you workaround is working fine then that's probably a simpler thing to do.

**Comment by zwang** [comment]
@diegosanchezr  Thank you for the POC fix and thoughts. Sorry for the late response. I finally got some time to revisit this issue. 

So I seems have figured out the issue with overlapping bubble messages. It was due to I was trying to do some data update optimization. I was trying to delay the enqueuing of data update in my code if the view is at background. And enqueue the data update in `viewWillAppeart` if datasource updated. This seems to cause problem. After I moved the code to `viewDidAppear`, it all seems working well. I guess before `viewDidAppear`, there is a lot of transition going on. So it seems to be better to wait until those transition done. 

I tried the POC fix, it works pretty well without any modification. I tried to test as much as I can and didn't find any issues. Now everything seems to be working well when I switch views back and forth. My guess is since it invalidate the layout context and it will re-trigger the `adjustCollectionViewInsets` after bound and orientation changed

Regarding the things missing you mentioned above, it seems 1 and 4 works pretty well. 2 seems not needed since no problem found with the fix. And for 3, it seems to be the reason leading the overlapping of bubble message. The contents move up due to contentSize shrinks.  

Anyway, all my issue is fixed now and I am happy to move on with this. (maybe revisit later if you feel like so but I feel it is working pretty well)

Thank you very much for you help. Really appreciate it. 👍

**Comment by diegosanchezr** [comment]
Glad to hear it helped. If I remember correctly my PoC would at least break pagination without implementing 1

**Comment by zwang** [comment]
I see. I will check it out and test it more then. Thank you for the help! :)

**Comment by zwang** [comment]
@diegosanchezr You are right. I did notice that scrolling up for older messages cause the view go back to bottom at the first time. I did a fix based on your suggestion on item 1 mentioned above.  So now the code looks like below:

    public override func invalidateLayoutWithContext(context: UICollectionViewLayoutInvalidationContext) {
        guard let layoutModel = self.layoutModel, delegate = self.delegate else {
            super.invalidateLayoutWithContext(context)
            return
        }
        let newLayout = delegate.chatCollectionViewLayoutModel()
        let oldContentSize = layoutModel.contentSize
        guard oldContentSize.width != newLayout.contentSize.width else {
            super.invalidateLayoutWithContext(context)
            return
        }
        self.layoutModel = delegate.chatCollectionViewLayoutModel()
        self.layoutNeedsUpdate = false
        let contentSizeDiff = self.layoutModel.contentSize.height - oldContentSize.height
        context.contentOffsetAdjustment = CGPoint(x: 0, y: contentSizeDiff)
        super.invalidateLayoutWithContext(context)
    }

After the fix, the pagination issue is fixed. I haven't found any other issue yet. 

Thanks again for the help. Sorry for the late update. Just got some time to try out your suggestion. :)
