### ISSUE TITLE
Are there any documentations for objective-c

### ISSUE THREAD

**Issue by NeilNie** [badoo/Chatto#15]
Hi, this is a stupid questions. I want to use this framework in objective-c and do you have any documentations for objective-c? Thank you very much!

**Comment by diegosanchezr** [comment]
Swift classes can't be inherited in objective-c, so your custom ChatViewController subclass needs to be written in Swift. On that basis, nothing in Chatto is thought to be objective-c compatible, so you're responsible to write, if needed, an adapter layer that interacts with your existing objective-c codebase.

**Comment by NeilNie** [comment]
Got it, thank you very much. I appreciate your help. Happy holidays!

**Comment by apwelsh** [comment]
I know this is very old, but for the sake of others, I used swift to create the ChatViewController, and exposed the init functions to objective C with the @objc annotation.  Then I used the new init method to call the constructor. from Objective C.  What I expose to Objective C from the ChatViewController is very minimal, and perfect for my needs.

In my ChatViewController.swift file, I use the following to initialize the class:

```
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        self.setupViewController()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        self.setupViewController()
    }
    
    @objc
    convenience init(conversation: Conversation) {
        self.init(nibName: "ChatViewController", bundle:nil)
        NSLog("Initialized with Conversation: %@", conversation.dictionaryOfProperties())
        self.conversation = conversation
    }
    
    func setupViewController() {
        self.conversation = nil;
        self.remoteConfig = PREngine.sharedInstance().remoteConfig
    }

```
In my Objective C class, I construct my ChatViewController like this:
`ChatViewController *viewController = [[ChatViewController alloc] initWithConversation:conversation];`
and I added the following import to my Objective C file:
`#import "MyAppName-Swift.h"`

There really isn't much more to it, except that you will need the bridging file which you will need to add any Objective-C imports into so that you can use the classes in swift.
