### ISSUE TITLE
Xcode 8, Swift 3 - dramatic changes have broken the chat UI paradigm

### ISSUE THREAD

**Issue by pkasson** [badoo/Chatto#229]
Having been forced to handle all the breaking code from 3.0, the Chatto app now no longer works.  With all the new generics and UI updates, going from pre 3.0 to 3.0 is painful and not working .   Is there a migration guide to help moving between these releases ?

**Comment by diegosanchezr** [comment]
There's no special guide to transition from Chatto 2.0 to Chatto 3.0 since we've just basically run the migrator - it should just be a standard migration of Swift code from version 2 to 3. If you have specific questions we may be able to help

**Comment by zwang** [comment]
I just finished updating to Chatto v3.0. I have created about 5-6 groups of (sub)classes which supports our custom messages (Like custom bubble view, collectionViewCell, presenter, builder, viewModel etc, I have 40 files in total related to Chatto library updated because of this). It did take me 2-3 hours to figure out and make sure everything works well with Chatto (I have many other stuff to update to Swift 3 too at the same time, the whole upgrade process took about 7-8 hours). 

Here are what I learned regarding the upgrade (specifically for this Chatto library given the generics usage in the library and in my app):
1. It seems sometimes Xcode 8 will show you some random errors regarding the classes but the problem might be in other classes. For example, Xcode keeps saying there is issues with my builder/presenter, which is very confusing, but after I fix the collection cell view and bubble view first (due to enum case changes), then the previous error of presenter and builder is gone. So I suggest you fix the other easier ones and then tackle the confusing ones, sometimes those confusing ones just went away after you make sure the other classes they depends on have no problems.
2. If you use the automatic syntax converting function, some of the automatic conversion are actually wrong. And sometimes it keeps changing back and forth. So to avoid this, I suggest following tip 1 mentioned above and then later do another syntax conversion. 
3. I also check similar classes in the source code of Chatto to compare with my implementation to make sure I am doing right with my subclasses and custom classes

Hope this helps.

**Comment by pkasson** [comment]
I had it all working, and after the migration to 3 (that was painful overall), it runs, but the chat history (bubbles) is blank, and the send button is missing. 

Here is what I had before (minimalistic, only texting for now):

```
 return
  [
   TextMessageModel.chatItemType:
    [
    TextMessagePresenterBuilder(
     viewModelBuilder: TextMessageViewModelDefaultBuilder(),
     interactionHandler: TextMessageHandler(baseHandler: self.baseMessageHandler)
    )
   ],
```

for "createPresenterBuilders" within my custom chat VC, and now (need to cleanup):

```
  let textMessagePresenter = TextMessagePresenterBuilder(viewModelBuilder: DemoTextMessageViewModelBuilder(), interactionHandler: DemoTextMessageHandler(baseHandler: self.baseMessageHandler))
  
  return [
   DemoTextMessageModel.chatItemType: [
    textMessagePresenter
   ],
   
   SendingStatusModel.chatItemType: [SendingStatusPresenterBuilder()]
//   TimeSeparatorModel.chatItemType: [TimeSeparatorPresenterBuilder()]
  ]
```

Q1.  Is this a datasource (Fake data source) issue ?
Q2.  Where did the send button go
Q3.  What is the TimeSeparaterModel that was part of the demo app for ?

Thanks !
