### ISSUE TITLE
Chatto and live data

### ISSUE THREAD

**Issue by albarq** [badoo/Chatto#321]
Hi,

Is there any example code with live data.... ?  I am facing difficulties in understand how to send data and to work with FakeDataSource

please help!!

**Comment by AntonPalich** [comment]
Hi @albarq. `FakeDataSource` is implementation of `ChatDataSourceProtocol` in example app. In your own app you should have your own implementation of `ChatDataSourceProtocol` that loads data from your servers. When data is loaded you should trigger delegate call `chatDataSourceDidUpdate()`.

Let me show you an example. In Badoo we have `BMAChatViewController` which is subclass of `BaseChatViewController`. Also, we have our own implementation of `ChatDataSourceProtocol` called `BMAChatViewModel`. It is responsible for loading data from server and from cache. When data loaded either from cache or server `BMAChatViewModel` calls `self.delegate?.chatDataSourceDidUpdate()`. That's it.

```swift
class BMAChatViewController: BaseChatViewController {
    override func viewDidLoad() {
        ...
        self.viewModel = BMAChatViewModel()
        self.dataSource = self.viewModel
        self.viewModel.load()
    }
}

class BMAChatViewModel: ChatDataSourceProtocol {
    func load() {
        // load data from cache or server
        self.delegate?.chatDataSourceDidUpdate()
    }
}
```

This is very simplified example, but it should help you to understand what to do

**Comment by albarq** [comment]
Thank you for your explanation ..  for me i have finished the parts of loading all messages .. but my problems are: 
1- how to send new messages to server ... 
2- how  do live updating  for current received messages... 
3- how to update current status of message 
4- Right now i am using alamofire ... am I right?  or do I need to switch to socket.io?

**Comment by AntonPalich** [comment]
Chatto is UI framework. It's not responsible for client-server communication. Each app should implement it separately. It's up to you what solution to use. Regarding your questions from UI point of view:

1. Please, check `DemoChatViewController` in example app.

```swift
    private func createTextInputItem() -> TextChatInputItem {
        let item = TextChatInputItem()
        item.textInputHandler = { [weak self] text in
            self?.dataSource.addTextMessage(text)
        }
        return item
    }
```

In `textInputHandler` you can handle a new text message (same for `PhotoChatInputItem` and `photoInputHandler` parameter for photo message). It's up to you how to deliver this message to server. 

2. Whenever your data is updated you need to notify view controller that data source changed using `self.delegate?.chatDataSourceDidUpdate()`. Everything else will be handled automatically.

3. Your data source should track message status and update appropriate properties on your model. For example, when you start sending message to the server you can change `status` property of your `MessageModelProtocol` implementation to `.sending` value. Whenever state changed just call `self.delegate?.chatDataSourceDidUpdate()`

4. Again, it's up to you. In Badoo app we are using sockets, because it allows you to have two way communication between client and server.
