### ISSUE TITLE
Is there an upgrade plan for Swift 4?

### ISSUE THREAD

**Issue by alexanderkhitev** [badoo/Chatto#331]
Hi! Is there an upgrade plan for Swift 4?

**Comment by AntonPalich** [comment]
Hi @alexsanderkhitev! We will migrate to Swift 4 in one of the latest beta.

**Comment by alexsanderkhitev** [comment]
Hi @AntonPalich. It's a good news!

**Comment by irace** [comment]
@AntonPalich Is there a branch that works with Swift 4 and Xcode 9? The `swift4` branch of the `ChattoAdditions` pod does not currently compile...

**Comment by Allow2CEO** [comment]
Second that, trying to use chatto in an extension and ChattoAdditions will not compile

**Comment by jba52739088** [comment]
is there any method to fix it?

**Comment by alexanderkhitev** [comment]
Hi @Allow2CEO Are you trying to build for the App Store?

**Comment by Allow2CEO** [comment]
Yes

**Comment by alexanderkhitev** [comment]
@Allow2CEO Go to the project menu My app -> My app target -> Build Settings -> Swift compiler code generator -> Optimization level -> Release -> set to None [-Onone]

![git](https://user-images.githubusercontent.com/12511909/31009840-d66debfa-a519-11e7-96b7-973dcc4f68ae.png)

**Comment by Graystripe17** [comment]
Chatto currently works for Swift 3.2 right? I compile with ChattoAdditions on "Swift Language Version 3.2" for debug and release but it still gives off 18 syntax errors relating to casting NS data structures.

**Comment by justdan0227** [comment]
Seeing the same message with regards to NS DataStructures when using Swift4 and setting the pod to 3.2

**Comment by ploper187** [comment]
I am also having issues making use of the Chatto framework. Upon installing using Cocoapods, I have 18 issues, just like @Graystripe17 ... 

Is this a known issue or simply a mistake on our part?

**Comment by AntonPalich** [comment]
@Graystripe17, @justdan0227, @ploper187 The last Chatto version that supports Swift 3.2 is 3.2.0. The master branch uses Swift 4. 

You see errors because Swift version specified in your Pod project and Swift version used in Chatto differs. Make sure, that they match. 

Several examples:
1. Project and pods uses Swift 3.2. Chatto points to 3.2.0. You don't need to do anything.
2. Project and pods uses Swift 4. Chatto points to master branch. You don't need to do anything.
3. Project and pods uses Swift 4. Chatto points to 3.2.0. You need to change a Swift version for Chatto and ChattoAdditions to Swift 3.2.
4. Project and pods uses Swift 3.2. Chatto points to master branch. You need to change a Swift version for Chatto and ChattoAdditions to Swift 4.

This is an example how you can change Swift version for specific pods:

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|

      if target.name == 'Chatto' || target.name == 'ChattoAdditions`
        config.build_settings['SWIFT_VERSION'] = '3.0'
      else
        config.build_settings['SWIFT_VERSION'] = '4.0'
      end

    end
  end
end
```
