### ISSUE TITLE
Question: How to get event "begin typing" and "and typing"?

### ISSUE THREAD

**Issue by twox** [badoo/Chatto#40]
Hi,
How I can to get event "begin typing" and "end typing" in ChatViewController?
The class ChatInputBarPresenter has not delegates for these events. The ChatInputBarDelegate is not public protocol and he hidden in ChatViewController...

**Comment by diegosanchezr** [comment]
Hi @twox, sorry for the late response. As you say there are no notifications for such events at this moment. This is something we definitely would like to have, so don't hesitate in making a contribution.

**Comment by bcamur** [comment]
Hi, I implemented a solution for this and committed it to my fork. Can you check out my commit [here](https://github.com/bcamur/Chatto/commit/32869d670231dfb8caf80e90a7e1a69c7dbc98d1). If you think it's ok I can create a PR. I have tested this using my ChatViewController and it seems to work without a problem for now.

**Comment by diegosanchezr** [comment]
@AntonPalich can you take a look?

**Comment by twox** [comment]
Thanks @bcamur for your solution!
I tested your solution in my project and it works fine.

**Comment by bcamur** [comment]
You are welcome @twox. Please let me now if something unexpected happens👍

**Comment by AntonPalich** [comment]
Hi @bcamur,
You solutions is good and solves specific problem, but let's think about more general issue. As user, i want to be able to react on some events from input bar: in some cases i would use events for typing timers, in other cases i would like to collect some analytics, etc. I don't think that specific behaviour should be implemented in framework, instead of that we should provide API that will allow you to build whatever you want. Delegation is great pattern in this case, but unfortunately it (ChatInputBarDelegate) was used for internal purposes, but now it will become public #50

**Comment by bcamur** [comment]
Hi @AntonPalich, I agree with you -that the framework should be flexible enough to allow users build all kinds of functionality- and your solution makes that possible, which is very nice. However I also think that indicators like "xxxxx is typing..." have become kind of a core functionality in IM apps (I guess we have WhatsApp to thank for that :smiley:) and it might be a good idea to provide a default implementation somewhere in the framework. Thank you you for the solution btw, it looks awesome :+1: .
