### ISSUE TITLE
Default decorationAttributes

### ISSUE THREAD

**Issue by mrchenhao** [badoo/Chatto#49]
```
let newDecoratedItems = self.chatItemsDecorator?.decorateItems(newItems) ?? newItems.map { 
DecoratedChatItem(chatItem: $0, decorationAttributes: nil) 
}
```

there is no default decorationAttributes.
it will case the crash

**Comment by diegosanchezr** [comment]
Chatto framework makes decorationAttributes optional, that's by design. You can have your our presenters and even own CollectionLayout that doesn't use them.

That said, ChattoAdditions's BasePresenter not only requires attributes conforming to ChatItemDecorationAttributesProtocol, but a more concrete type (ChatItemDecorationAttributes).

As long as you use ChattoAdditions classes is your responsibility to provide the decoration attributes they need.

**Comment by mrchenhao** [comment]
Thank you to replay me.
I read the source code and I know it is optional
```
 let newDecoratedItems = self.chatItemsDecorator?.decorateItems(newItems) ?? newItems.map { DecoratedChatItem(chatItem: $0, decorationAttributes: nil) }
```
It seems that the default value of the decorationAttributes is nil

if I use `TextMessagePresenter`, it doesn't override the `public override func heightForCell(maximumWidth width: CGFloat, decorationAttributes: ChatItemDecorationAttributesProtocol?) -> CGFloat`

so I will invoke the `BaseMessagePresenter` `heightForCell` 
```
guard let decorationAttributes = decorationAttributes as? ChatItemDecorationAttributes else {
            assert(false, "Expecting decoration attributes")
            return 0
        }
```

so it will assert.

**Comment by diegosanchezr** [comment]
You need to create your own decorator. Look at ChatItemsDemoDecorator in ChattoApp.
