### ISSUE TITLE
iPhone X input bar selecting bug

### ISSUE THREAD

**Issue by Ogerets** [badoo/Chatto#514]
Steps to reproduce in sample ChattoApp
* Select photo input item from input bar
* Select text input item from input bar
* Got bug demonstrated on screenshot. Input bar shifted. No way to send messages anymore.

![simulator screen shot - iphone x - 2018-09-12 at 12 09 06](https://user-images.githubusercontent.com/20406383/45414788-d331e180-b684-11e8-83e7-984c6aac625e.png)

**Comment by AntonPalich** [comment]
Hey, @Ogerets Can you provide your environment and Chatto version? Looks of for me. Checked on the latest master on iPhoneX 11.4 simulator in Xcode 9.4.1

**Comment by gdelarosa** [comment]
I am experiencing the same bug as well. Selecting the keyboard or photo icon will display okay the first time but selecting a second time will produce the issue. Using Xcode 9.4.1. and iPhone X iOS 11.4

**Comment by Ogerets** [comment]
![2](https://user-images.githubusercontent.com/20406383/46489093-338feb00-c80d-11e8-886a-9358b004575f.jpg)

I'm able to reproduce bug even in badoo app

**Comment by dloic** [comment]
Seeing same issue on my side. Could this be related to https://forums.developer.apple.com/thread/108775? I'm seeing different values for UIKeyboardFrameEndUserInfoKey.

**Comment by AntonPalich** [comment]
Seems like an iOS 12 issue. Here is an example: https://github.com/AntonPalich/KeyboardIssueExample
I've reported it to Apple. I'll try to find a workaround.

**Comment by Ogerets** [comment]
@AntonPalich Me and *gdelarosa* just said above that we experienced this issue on iOS 11.4. So it's not an iOS 12 issue.

**Comment by AntonPalich** [comment]
@Ogerets I've tried on different simulators (iPhone 8, 8 Plus, X) on iOS 11.4 but was never able to reproduce the issue. Maybe, I was extremely lucky. If you check out an example project you will see that this issue is reproducible on iOS 12 only, but not on iOS 11.4.

Could you, please, help me to understand what am I doing wrong? Can you record a video or provide steps to reproduce? I've tried with your steps (attached a video [ios_11.4.zip](https://github.com/badoo/Chatto/files/2453381/ios_11.4.zip)  ~20 Mb) but didn't encounter the issue. Sorry, but I can't fix something that I can't reproduce.

**Comment by Ogerets** [comment]
@AntonPalich I've just checked and can confirm that issue no longer reproducable on iOS 11.4. Only iOS 12. Is it some sort of weird Apple magic after updates? Sorry for disturbing, just wanted help you.

**Comment by amedakedo** [comment]
I believe this is an iOS bug. (Tested on iOS 12)
It only happens on iPhone X, XS, XS Max, and XR (bezel-less iPhones). 
The layout for the system-keyboard on these devices is different, as the dictation and globe (keyboard switcher) buttons are below the space-bar row of the keyboard.

The default behavior for when you switch the inputView on a textView is for the custom inputView to have the same height as the system-keyboard

For some reason this behavior doesn't work as expected on bezel-less iPhones. The height given to the custom inputView is actually smaller than the system-keyboard. Also, even though the height is different the `UIKeyboardWillChangeFrame` notification will not trigger (since the height should've been the same in the first place)

To work around this you would have to set a custom height to your inputView, as this will cause the `UIKeboardWillChangeFrame` notification to trigger and update the toolbar's position on screen accordingly.

P.S:  I'm not actually using Chatto atm.

How to setup your custom inputView with a fixed height:
↓ for some reason this didn't work for me
> https://stackoverflow.com/a/33296667

So I used this instead (I'm not sure about Chatto but this how I fixed it for my Project)
> https://stackoverflow.com/a/50100631

For this solution you don't have to subclass UIInputView, you could simply define your inputView as an `UIInputView` and set its `inputView.allowsSelfSizing = true` and then setup the frame as you'd please.

**Comment by AntonPalich** [comment]
@amedakedo Thank you for such great help! I've fixed the issue in #530

**Comment by amedakedo** [comment]
@AntonPalich sure No problem 👍
