### ISSUE TITLE
potential memory leak because of _chatDataSource not weak.

### ISSUE THREAD

**Issue by wangjiejacques** [badoo/Chatto#582]
why not make the `_chatDataSource` weak like the `UITableView#dataSource`?

**Comment by wiruzx** [comment]
Hey @wangjiejacques, 
It's not weak intentionally, as nobody else is going to have strong reference to it in most cases.
Thanks

**Comment by wangjiejacques** [comment]
Hi @wiruzx, in my case,  my first implementation was this,
I create a custom `ChatViewController: BaseChatViewController, ChatDataSourceProtocol`, and I call 
```
ChatViewController#setChatDataSource(self, triggeringUpdateType: nil)
```
I think many people will try to implement the custom data source like this, am I wrong?

**Comment by wiruzx** [comment]
@wangjiejacques That makes sense, it's probably very intuitive to conform `BaseChatViewController` to `ChatDataSourceProtocol`, as people usually do with `UITableViewDataSource`.
However, since we try to follow SOLID principles, we usually create a separate object for our DataSource.
I agree that the name of the protocol could be misleading, and we're already having internal discussions about renaming it.
Thanks!
