### ISSUE TITLE
Photo message gets reset on each dataset change

### ISSUE THREAD

**Issue by fgulan** [badoo/Chatto#610]
In `release-3.5.0` branch there is a somehow weird behavior with photo messages (maybe with text as well but it is not noticeable). Each time data source items are updated and update is triggered, it will always create new view model for cell/model and it will cause the cell to reload.

You can examine this behavior on `Overview` example, scroll to photo message and try sending a text message, when you send it you'll see that photo is loading again.

As a workaround I can override:

```swift
    let isItemUpdateSupported = true

    func update(with chatItem: ChatItemProtocol) { }
```

which will avoid creating new presenter due to `isItemUpdateSupported` is true, and will avoid creating new view model since I'm not calling super implementation from `BaseMessagePresenter`, but I'm not sure if this is correct, or mentioned behavior is a bug

**Comment by Rouix** [comment]
Same for me. Any update of data source caused re-creation all of presenters & viewModels

in

`            if let oldChatItemCompanion = oldItems[decoratedChatItem.uid], oldChatItemCompanion.chatItem === chatItem {
                presenter = oldChatItemCompanion.presenter
            } else {
                presenter = self.createPresenterForChatItem(decoratedChatItem.chatItem)
            }
`

first branch is never executing.

**Comment by AntonPalich** [comment]
@fgulan @Rouix Since the beginning, message presenters were reused only for the same instance of an item. We've added an ability to control that behaviour by changing `isItemUpdateSupported` in a message presenter. If it's set to `true` then presenter will be reused for an item with the same identifier.

@fgulan If you decide to keep an existing view model make sure that it's updated when you update a presenter with an updated item.

**Comment by fgulan** [comment]
Thanks @AntonPalich!
